### ISSUE TITLE
Redirect through logins

### ISSUE THREAD

**Issue by dqwiki** [UTRS/utrs#121]
With the implementation of OAuth, login destinations are not preserved. Would be nice to get this functionality back.

**Comment by Salvidrim** [comment]
Yea, otherwise the on-wiki {{utrs}} template becomes useless

~ Benoit / Salvidrim<http://www.salvidrim.net>
[Sent from my Nexus 6P]
________________________________
From: dqwiki
Sent: Sat Feb 04 18:36:47 EST 2017
To: UTRS/utrs
Cc: Subscribed
Subject: [UTRS/utrs] Redirect through logins (#121)


With the implementation of OAuth, login destinations are not preserved. Would be nice to get this functionality back.

**Comment by dqwiki** [comment]
Work in progress that I need to step away from for a bit. It's currently working so that the login splash gets a redirect command, but that command is flawed. Working to resolve.
