### ISSUE TITLE
Redesign Userright flags

### ISSUE THREAD

**Issue by dqwiki** [UTRS/utrs#34]
Flags:
Suspended Tool User (No access)
Tool User (ENWP Admins - Appeal view/process)
Tool Administrator (Manage Appeals, Users, Bans, etc.)
ENWP CU (View CheckUser data)
ENWP OS (and eventually oversight of data - when implemented, does not auto have CU flag)
WMF Staff (All the above rights, without being dependent, also emergency release per #21)
Tool Developer (Site wide configuration changes, all above permissions)

Marking #32 now a duplicate per this expansion

**Comment by Salvidrim** [comment]
Is CU & OS planned to be a single user-right? Won't that be a problem for non-CU Oversighters and non-OS Checkusers?

**Comment by dqwiki** [comment]
Damnit, yes. Fixed the plan.

**Comment by Salvidrim** [comment]
Will these be like, nested one within another? A tool admin is also automatically also a user? Someone with Dev right is also automatically a tool admin & tool user, so that the account doesn't have to have 2-3 redundant user rights?

It makes sense for a user > tooladmin > dev progression (a dev is also a tooladmin & user, a tooladmin is also a user), but CU and OS should remain separate; we have both non-tooladmin CU/OS and non-CU/OS tooladmins and should be able to offer these layers of access separately. In theory, of the two non-WMF devs, only you is also CU/OS, should the same problem arises if Chris retains the Dev user right

Of course, the WMF user right would include user, tooladmin, CU and OS (and emergency release) without the need to be in all individual user groups.

Am I also correct in understanding that in your plan, WMF would not have Dev access (like they currently do)?

**Comment by dqwiki** [comment]
Every userright will inherit the permissions of the previous group unless noted otherwise. ...actually I take that back, they shouldn't be able to manage users. I'll have to make a chart of which userrights will be assigned to which groups. But the general idea is still correct.

Either way, it will be made sure that as few rights tags as possible are needed.

The WMF could force access to it if they needed to via Legal and through the WMF Labs Administrators and go right into the database, but they don't really have direct access to anything right now.

**Comment by Salvidrim** [comment]
So CU/OS will also be tool admins? That's a pretty significant change. I don't think it'll specifically be a problem though, but I still think we should have both CU and OS flags be "outside" and independent from the main progressison.

Suspended > User > Admin > Dev
CU/OS set individually for all levels
WMF being admin + CU/OS packaged

**Comment by dqwiki** [comment]
I realized yesterday when I said above that that appeared to be an unattended effect. That wont be the case, again i need to make a perms chart to figure this out.

**Comment by dqwiki** [comment]
Of note, issue #43 which should be dealt with in this fix.

**Comment by dqwiki** [comment]
The main problem trying to be solved here is already dealt with.
